# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

name = "Amit"

for i in range(3):
    print(name)

a = 10
b = 20
c = 30

sum = a + b + c

print(sum)

a = "Hello"
b = "World"
c = "Python"

result = a + b + c

print(result)

for i in range(1, 11):
    print(7 * i)

print()

for i in range(1, 11):
    print(9 * i)

n = int(input("Enter a number: "))

for i in range(1, 11):
    print(n * i)

n = int(input("Enter a number: "))

sum = 0

for i in range(1, n + 1):
    sum = sum + i

print(sum)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

print("Maximum =", max(a, b, c))

n = int(input("Enter a number: "))

sum = 0

for i in range(1, n + 1):
    if i % 7 == 0 and i % 9 == 0:
        sum = sum + i

print("Sum =", sum)

n = int(input("Enter a number: "))

sum = 0

for i in range(2, n + 1):
    count = 0

    for j in range(1, i + 1):
        if i % j == 0:
            count = count + 1

    if count == 2:
        sum = sum + i

print("Sum =", sum)

def oddsum(n):
    sum = 0

    for i in range(1, n + 1):
        if i % 2 != 0:
            sum = sum + i

    return sum


n = int(input("Enter a number: "))

print("Sum =", oddsum(n))

def primesum(n):
    sum = 0

    for i in range(2, n + 1):
        count = 0

        for j in range(1, i + 1):
            if i % j == 0:
                count = count + 1

        if count == 2:
            sum = sum + i

    return sum


n = int(input("Enter a number: "))

print("Sum =", primesum(n))